
version: 2.1

jobs:
  py3:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: python -m pip install PyPDF2 --user
      - run: python pdf_merging merge.py
      - run: python -m unittest tests/test_merge.py

workflows:
  version: 2
  build:
    jobs:
      - py3
