
version: 2.1

jobs:
  py3:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/pdf_merging
    steps:
      - run: python -m unittest
      - run: python ~/pdf_merging/pdf_merging/merge.py

workflows:
  version: 2
  build:
    jobs:
      - py3
